Traceback (most recent call last):
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib_inline.backend_inline

# Plot settings
plt.style.use(
    "https://github.com/aeturrell/coding-for-economists/raw/main/plot_style.txt"
)
matplotlib_inline.backend_inline.set_matplotlib_formats("svg")

# Set max rows displayed for readability
pd.set_option("display.max_rows", 6)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRemoteDisconnected[0m                        Traceback (most recent call last)
[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/matplotlib/style/core.py[0m in [0;36muse[0;34m(style)[0m
[1;32m    114[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 115[0;31m                 [0mrc[0m [0;34m=[0m [0mrc_params_from_file[0m[0;34m([0m[0mstyle[0m[0;34m,[0m [0muse_default_template[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    116[0m                 [0m_apply_style[0m[0;34m([0m[0mrc[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/matplotlib/__init__.py[0m in [0;36mrc_params_from_file[0;34m(fname, fail_on_error, use_default_template)[0m
[1;32m    797[0m     """
[0;32m--> 798[0;31m     [0mconfig_from_file[0m [0;34m=[0m [0m_rc_params_in_file[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mfail_on_error[0m[0;34m=[0m[0mfail_on_error[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    799[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/matplotlib/__init__.py[0m in [0;36m_rc_params_in_file[0;34m(fname, transform, fail_on_error)[0m
[1;32m    726[0m     [0mrc_temp[0m [0;34m=[0m [0;34m{[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 727[0;31m     [0;32mwith[0m [0m_open_file_or_url[0m[0;34m([0m[0mfname[0m[0;34m)[0m [0;32mas[0m [0mfd[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    728[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/contextlib.py[0m in [0;36m__enter__[0;34m(self)[0m
[1;32m    112[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 113[0;31m             [0;32mreturn[0m [0mnext[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgen[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    114[0m         [0;32mexcept[0m [0mStopIteration[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/matplotlib/__init__.py[0m in [0;36m_open_file_or_url[0;34m(fname)[0m
[1;32m    697[0m             )
[0;32m--> 698[0;31m         [0;32mwith[0m [0murllib[0m[0;34m.[0m[0mrequest[0m[0;34m.[0m[0murlopen[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mcontext[0m[0;34m=[0m[0mssl_ctx[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    699[0m             [0;32myield[0m [0;34m([0m[0mline[0m[0;34m.[0m[0mdecode[0m[0;34m([0m[0;34m'utf-8'[0m[0;34m)[0m [0;32mfor[0m [0mline[0m [0;32min[0m [0mf[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/urllib/request.py[0m in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    221[0m         [0mopener[0m [0;34m=[0m [0m_opener[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 222[0;31m     [0;32mreturn[0m [0mopener[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mdata[0m[0;34m,[0m [0mtimeout[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    223[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/urllib/request.py[0m in [0;36mopen[0;34m(self, fullurl, data, timeout)[0m
[1;32m    524[0m         [0msys[0m[0;34m.[0m[0maudit[0m[0;34m([0m[0;34m'urllib.Request'[0m[0;34m,[0m [0mreq[0m[0;34m.[0m[0mfull_url[0m[0;34m,[0m [0mreq[0m[0;34m.[0m[0mdata[0m[0;34m,[0m [0mreq[0m[0;34m.[0m[0mheaders[0m[0;34m,[0m [0mreq[0m[0;34m.[0m[0mget_method[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 525[0;31m         [0mresponse[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_open[0m[0;34m([0m[0mreq[0m[0;34m,[0m [0mdata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    526[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/urllib/request.py[0m in [0;36m_open[0;34m(self, req, data)[0m
[1;32m    541[0m         [0mprotocol[0m [0;34m=[0m [0mreq[0m[0;34m.[0m[0mtype[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 542[0;31m         result = self._call_chain(self.handle_open, protocol, protocol +
[0m[1;32m    543[0m                                   '_open', req)

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/urllib/request.py[0m in [0;36m_call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    501[0m             [0mfunc[0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0mhandler[0m[0;34m,[0m [0mmeth_name[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 502[0;31m             [0mresult[0m [0;34m=[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    503[0m             [0;32mif[0m [0mresult[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/urllib/request.py[0m in [0;36mhttps_open[0;34m(self, req)[0m
[1;32m   1396[0m         [0;32mdef[0m [0mhttps_open[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mreq[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1397[0;31m             return self.do_open(http.client.HTTPSConnection, req,
[0m[1;32m   1398[0m                 context=self._context, check_hostname=self._check_hostname)

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/urllib/request.py[0m in [0;36mdo_open[0;34m(self, http_class, req, **http_conn_args)[0m
[1;32m   1357[0m                 [0;32mraise[0m [0mURLError[0m[0;34m([0m[0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1358[0;31m             [0mr[0m [0;34m=[0m [0mh[0m[0;34m.[0m[0mgetresponse[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1359[0m         [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/http/client.py[0m in [0;36mgetresponse[0;34m(self)[0m
[1;32m   1347[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1348[0;31m                 [0mresponse[0m[0;34m.[0m[0mbegin[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1349[0m             [0;32mexcept[0m [0mConnectionError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/http/client.py[0m in [0;36mbegin[0;34m(self)[0m
[1;32m    315[0m         [0;32mwhile[0m [0;32mTrue[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 316[0;31m             [0mversion[0m[0;34m,[0m [0mstatus[0m[0;34m,[0m [0mreason[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_read_status[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    317[0m             [0;32mif[0m [0mstatus[0m [0;34m!=[0m [0mCONTINUE[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/http/client.py[0m in [0;36m_read_status[0;34m(self)[0m
[1;32m    284[0m             [0;31m# sending a valid response.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 285[0;31m             raise RemoteDisconnected("Remote end closed connection without"
[0m[1;32m    286[0m                                      " response")

[0;31mRemoteDisconnected[0m: Remote end closed connection without response

The above exception was the direct cause of the following exception:

[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m/var/folders/x6/ffnr59f116l96_y0q0bjfz7c0000gn/T/ipykernel_78062/1003300902.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;31m# Plot settings[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m plt.style.use(
[0m[1;32m      5[0m     [0;34m"https://github.com/aeturrell/coding-for-economists/raw/main/plot_style.txt"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m )

[0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/matplotlib/style/core.py[0m in [0;36muse[0;34m(style)[0m
[1;32m    116[0m                 [0m_apply_style[0m[0;34m([0m[0mrc[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    117[0m             [0;32mexcept[0m [0mIOError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 118[0;31m                 raise IOError(
[0m[1;32m    119[0m                     [0;34m"{!r} not found in the style library and input is not a "[0m[0;34m[0m[0;34m[0m[0m
[1;32m    120[0m                     [0;34m"valid URL or path; see `style.available` for list of "[0m[0;34m[0m[0;34m[0m[0m

[0;31mOSError[0m: 'https://github.com/aeturrell/coding-for-economists/raw/main/plot_style.txt' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
OSError: 'https://github.com/aeturrell/coding-for-economists/raw/main/plot_style.txt' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles

