Traceback (most recent call last):
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
orig = ox.get_nearest_node(graph, (location.latitude, location.longitude))
dest = ox.get_nearest_node(graph, (lunch_loc.latitude, lunch_loc.longitude))
route = ox.shortest_path(graph, orig, dest)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [39][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m orig [38;5;241m=[39m [43mox[49m[38;5;241;43m.[39;49m[43mget_nearest_node[49m(graph, (location[38;5;241m.[39mlatitude, location[38;5;241m.[39mlongitude))
[1;32m      2[0m dest [38;5;241m=[39m ox[38;5;241m.[39mget_nearest_node(graph, (lunch_loc[38;5;241m.[39mlatitude, lunch_loc[38;5;241m.[39mlongitude))
[1;32m      3[0m route [38;5;241m=[39m ox[38;5;241m.[39mshortest_path(graph, orig, dest)

[0;31mAttributeError[0m: module 'osmnx' has no attribute 'get_nearest_node'
AttributeError: module 'osmnx' has no attribute 'get_nearest_node'
